[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "out"
  exclude = [
    # By file Path
    './out/_next/*',
    # By Glob pattern
    #'**/**/child-one.html'
  ]